spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: master
    password: masterLimbo0$
    driver-class-name: com.mysql.cj.jdbc.Driver
   # Specify DBMS
  jpa:
    database: MYSQL
    show-sql: true
    #HIbernate DDL Auti (create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080